### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by kylewillmon**
I assume @phylum-dev/integrations will handle this repository.

### CODE REVIEW

**Review by maxrake — CHANGES_REQUESTED** [review]
The file looks right, but the repo itself will need to be modified...to allow the group access:

image

@louislang might have to do this

**Comment by kylewillmon** [comment]
I am also second guessing this PR. Extensions can (and should) be written by just about anyone, so perhaps the write access to this repository should be every Phylum employee and any 2 code reviewers is fine. That may be why @louislang didn't add a `CODEOWNERS` file from the start.

**Comment by louislang** [comment]
Yeah, that was basically the idea @kylewillmon. I tried to add the entire Phylum org, but Github wouldn't let me do that. I think we can also just limit pushes to `main` to a handful of people (integrations being in that group).

**Comment by louislang** [comment]
Updated to give phylum-dev/integrations write permissions on this repository. So should be good to merge this in. Might take a second for that change to be reflected on this PR though.

**Comment by kylewillmon** [comment]
> Updated to give phylum-dev/integrations write permissions on this repository. So should be good to merge this in. Might take a second for that change to be reflected on this PR though.

If the idea is that the whole org owns this repo, then I think it makes more sense to go without a CODEOWNERS file.

**Pull request closed without merging**
